In [1]:

# Import numpy module
import numpy as np

# Example 1: Creation of 1D array
arr1=np.array([10,20,30])
print("My 1D array:\n",arr1)

# Example 2: create a 2D numpy array
arr2 = np.array([[10,20,30],[40,50,60]])
print("My 2D numpy array:\n", arr2)

# Example 3: Create a sequence of integers
# from 0 to 20 with steps of 3
arr= np.arange(0, 20, 3)
print ("A sequential array with steps of 3:\n", arr)

# Example 4: Create a sequence of 5 values in range 0 to 3
arr= np.linspace(0, 3, 5)
print ("A sequential array with 5 values between 0 and 5:\n", arr)

# Example 5: Use asarray() convert array
list = [20,40,60,80]
array = np.asarray(list)
print(" Array:", array)

# Example 6: Use empty() create array
arr = (3, 4)  # 3 rows and 4 columns
rr1 = np.empty(arr)
print(" Array with values:\n",arr1)

# Example 7:Use zero() create array
arr = np.zeros((3,2))
print("numpy array:\n", arr)
print("Type:", type(arr))

# Example 8: Use ones() create array
arr = np.ones((2,3))
print("numpy array:\n", arr)
print("Type:", type(arr))

# Create array from existing array
# Using copy()
arr=np.array([10,20,30])
arr1=arr.copy()
print("Original array",arr)
print("Copied array",arr1)

# Create array using = operator
arr=np.array([10,20,30])
arr1=arr
print("Original array",arr)
print("Copied array",arr1)


My 1D array:
 [10 20 30]
My 2D numpy array:
 [[10 20 30]
 [40 50 60]]
A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]
A sequential array with 5 values between 0 and 5:
 [0.   0.75 1.5  2.25 3.  ]
 Array: [20 40 60 80]
 Array with values:
 [10 20 30]
numpy array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Type: <class 'numpy.ndarray'>
numpy array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Type: <class 'numpy.ndarray'>
Original array [10 20 30]
Copied array [10 20 30]
Original array [10 20 30]
Copied array [10 20 30]


In [3]:

# Create a 2D numpy array
arr2 = np.array([[10,20,30],[40,50,60]])
print("My 2D numpy array:\n", arr2)

# Output
# My 2D numpy array:
# [[10 20 30]
# [40 50 60]]

print("Type:", type(arr2))
# Type: <class 'numpy.ndarray'>


My 2D numpy array:
 [[10 20 30]
 [40 50 60]]
Type: <class 'numpy.ndarray'>


In [4]:

# Example 1: Use numpy.append() function
arr = np.array([[0,2,4],[6,8,10]]) 
app_arr = np.append(arr, [13,15,17]) 

# Example 2: Appending array with axis=0
arr = np.array([[0,2,4],[6,8,10]]) 
app_arr=np.append(arr, [[5,7,9],[13,15,17]],axis = 0)

# Example 3: Use Append elements along axis 1
arr = np.array([[0,2,4],[6,8,10]]) 
app_arr=np.append(arr, [[5,7,9],[13,15,17]],axis = 1) 

# Example 4: Use appending array
arr = np.arange(7)  
arr1 = np.arange(9, 14)
arr2 = np.append(arr, arr1)
print("Appended arr2 : ", arr2)


Appended arr2 :  [ 0  1  2  3  4  5  6  9 10 11 12 13]


In [6]:

# Below are a quick example on arrangement with numpy

# Example 1: Generate array Use arange() with single argument
arr = np.arange(9)

# Example 2: Get the array Use arange() function  
arr = np.arange(1, 12)

# Example 3: Get the array Use arange()
# with custom step-size
arr = np.arange(3, 22, 4)

# Example 4: custom step-size
arr = np.arange(start=2, stop=22, step=3)

# Example 5: Get the array with float values
arr = np.arange(1.5, 5.5, 0.5)

# Example 6: Get the array with negatives
arr = np.arange(-13, -2)

# Example 8: providing negative arguments
arr = np.arange(-13, -2, 3)


In [9]:
import numpy as np
# Use numpy.arange() with single argument
# generate the array
arr = np.arange(9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [10]:
# Use numpy.arange() function
# Get the array  
arr = np.arange(1, 12)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [11]:
# Get the array with negatives values
arr = np.arange(-13, -2)
print(arr)

# providing negative arguments
arr = np.arange(-13, -2, 3)
print(arr)


[-13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3]
[-13 -10  -7  -4]


In [12]:
# Example 1: Use numpy.absolute() to get the absolute value
arr = np.array([-46])
arr2 = np.absolute(arr)

# Example 2: get the absolute values of multiple elements of 1-d array
arr = [4, -9, 14, -23, 32, -56]
arr2 = np.absolute(arr)

# Example 3: Use numpy.absolute() function to get 
# the absolute values of floating point
arr = [-15.7, 8.6, -7.1, 8.7, -19.2, 43.8]
arr2 = np.absolute(arr)

# Example 4: Use numpy.absolute() get the absolute values 
# of 2-D array elements
arr = np.array([[-12, 8, -23, 32], [49, -74, -92, 106]])
arr2 = np.absolute(arr)

# Example 5: Use numpy.absolute() function with complex numbers
arr = [4+7j, -5-9j, 16+13j, -8+17j]
arr2 = np.absolute(arr)

In [13]:
import numpy as np
arr = np.array([-46])

# Use numpy.absolute() to get the absolute value
arr2 = np.absolute(arr)
print(arr2)

[46]


In [14]:
import numpy as np

# Create an 1D input array
arr = [4, -9, 14, -23, 32, -56]

# get the absolute values of multiple elements of 1-d array
arr2 = np.absolute(arr)
print(arr2)

[ 4  9 14 23 32 56]


In [15]:
import numpy as np

# creating an 1D input array
arr = [-15.7, 8.6, -7.1, 8.7, -19.2, 43.8]

# Use numpy.absolute() function to get 
# the absolute values of floating point
arr2 = np.absolute(arr)
print(arr2)

[15.7  8.6  7.1  8.7 19.2 43.8]


In [16]:
import numpy as np

# creating an 2D input array
arr = np.array([[-12, 8, -23, 32], [49, -74, -92, 106]])

# Use numpy.absolute() get the absolute values 
# of 2-D array elements
arr2 = np.absolute(arr)
print(arr2)


[[ 12   8  23  32]
 [ 49  74  92 106]]


In [ ]:

# Below are a quick example

# Example 1: use numpy.split() function
arr2 = np.split(arr,4) 

# Example 2: use numpy.split() function to split 1-D numpy array
arr2 = np.split(arr,[2,3])  

# Example 3: Use split 2-D numpy array use numpy.split() function
arr = np.array([[15,28,57,65],[25,37,55,88]])
arr2 = np.split(arr, 2, axis=0)  

# Example 4: Use split array along axis=1
arr2 = np.split(arr, 2, axis=1)  

# Example 5: Use numpy.split() function to slicing
arr2 = np.split(arr, (2,3), axis=1)


In [17]:
import numpy as np
 
# creating an input array
arr = np.array([5,7,9,11,13,19,23,27])

# use numpy.split() function
arr2 = np.split(arr,4)  
print(arr2)

[array([5, 7]), array([ 9, 11]), array([13, 19]), array([23, 27])]


In [18]:
# use numpy.split() function to split 1-D numpy array
arr2 = np.split(arr,[2,3])  
print(arr2)


[array([5, 7]), array([9]), array([11, 13, 19, 23, 27])]


In [19]:
import numpy as np
 
# creating an 2D input array
arr = np.array([[15,28,57,65],[25,37,55,88]])

# Use split array along axis = 0
arr2 = np.split(arr, 2, axis=0)  
print(arr2)


[array([[15, 28, 57, 65]]), array([[25, 37, 55, 88]])]


In [20]:
# Use split array along axis=1
arr2 = np.split(arr, 2, axis=1)  
print(arr2)

[array([[15, 28],
       [25, 37]]), array([[57, 65],
       [55, 88]])]


In [ ]:
# Example 1: Use numpy.mutiply() function and 
# get the matrix multiplication
arr2 = np.multiply(arr, arr1)

# Example 2: Get the certain rows multiplication
arr2 = np.multiply(arr[ 0,: 2], arr1[ 1,: 2])

# Example 3: Get dot product of arrays
arr = np.array([[1, 3 ],
                [4, 1 ]])
arr1 = 2
arr2 = np.dot(arr,arr1)

# Example 4: Use numpy.dot() function
# Get the product of two arrays
arr2 = np.dot(arr,arr1)

# Example 5: # Use numpy.matmul() function
# Get the product 
arr2 = np.matmul(arr,arr1)

In [21]:
import numpy as np
# Create a numpy two dimensional arrays
arr = np.array([[2, 4, 3, 1],[2, 3, 6, 1]])
arr1 = np.array([[2, 1, 5, 2],[4, 8, 3, 2]])
                 
# Use numpy.mutiply() function and 
# get the matrix multiplication
arr2 = np.multiply(arr, arr1)
print(arr2)

[[ 4  4 15  2]
 [ 8 24 18  2]]


In [22]:
# Get the certain rows multiplication
arr2 = np.multiply(arr[ 0,: 2], arr1[ 1,: 2])
print(arr2)

[ 8 32]


In [23]:
arr3 = np.multiply(arr[ 1,: 3], arr1[ 0,: 3])
print(arr3)

[ 4  3 30]


In [24]:
# Get dot product of arrays
arr = np.array([[1, 3 ],
                [4, 1 ]])
arr1 = 2
arr2 = np.dot(arr,arr1)
print(arr2)

[[2 6]
 [8 2]]
